name: Nike Job Monitor

on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

permissions:
  issues: write
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run Monitor
        run: python monitor.py
